### ISSUE TITLE
Will this project solve the crash problem in the emulator

### ISSUE THREAD

**Issue by lunasama666** [4pii4/PiePerseus#1]
perseus often crash in emulator

**Comment by 4pii4** [comment]
In my 6 months of using Perseus it only crashes when:
* The config file is incorrect due to any of the following:
  * Line endings (i.e. copying the config from your windows machine and pasting it in the emulator)
  * Wrong or missing key/value
  * Credit removed (the `original repo...` thing)
* Too many planes in a battle
